### ISSUE TITLE
Уведомления об ошибках

### ISSUE THREAD

**Issue by gaisin** [dvabidonamoloka/standupstoreparser#7]
Необходимо добавить оповещения по почте или на отдельный канал в телеграме о том, что в скрипте что-то пошло не так, например, возник какой-то эксепшн.
Предлагаю разобраться с отправкой писем на почту, предполагаю, что это будет функция в `notifications`.

**Comment by OdintsovTim** [comment]
Опиши, пожалуйста, подробнее задачу. Тебе нужна функция, которую ты сам будешь вставлять в участки кода, которые тебе нужны? То есть принципиально ничем не отличающаяся от функции `post_to_channel`?

**Comment by gaisin** [comment]
> Тебе нужна функция, которую ты сам будешь вставлять в участки кода, которые тебе нужны?

Да, я бы хотел использовать примерно так:
```python
try:
   do_something()
except Exception as e:
    LOG.error(f"Exception happened: {e})
    susp.notifications.send_exception_email(e)
```
То есть я передаю в функцию эксепшн, который я поймал, а функция сама вытащит из него трейсбэк, добавит текущее время, сформирует текст письма, сформирует тему письма с кодом ошибки и отправит на имейлы, указанные в `settings.py`.

Скорее всего пригодится модуль `traceback`, например, нашел вот такой способ: https://stackoverflow.com/a/54083435
