### ISSUE TITLE
Логи в stdout

### ISSUE THREAD

**Issue by gaisin** [dvabidonamoloka/standupstoreparser#9]
Хотелось бы, чтобы логи записывались в указанный файл и одновременно выводились в stdout — нужно, чтобы логи можно было хранить в файле и смотреть их через `docker logs`

**Comment by gaisin** [comment]
Теоретически для этого надо к логгеру прикрутить два разных хэндлера, на практике не тестировал, надо разобраться и допилить

**Comment by OdintsovTim** [comment]
LOG.error выводится в stdout , нужно чтобы debug и info тоже выводились?
